title: Con chó
description: Lessons learnt from a whole life wasted

markdown: kramdown
theme: jekyll-theme-architect

gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 10

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

disqus:
  shortname: mahpahh
